### ISSUE TITLE
Breadcrumb separator spacing issue

### ISSUE THREAD

**Issue by heruan** [twbs/bootstrap#17473]
In `v4.0.0-alpha` the breadcrumb separator spacing behaves differently when subsequent `<li>`s are separated by whitespace or not in the markup source.

```html
<ol class="breadcrumb">
    <li><a href="#">Home</a></li>
    <li><a href="#">Page</a></li>
</ol>
<ol class="breadcrumb">
    <li><a href="#">Home</a></li><li><a href="#">Page</a></li>
</ol>
```
produces:

![screen shot 2015-09-04 at 12 28 05](https://cloud.githubusercontent.com/assets/851745/9681733/af099b62-5300-11e5-9fb6-1811c12dbc7f.png)

See http://jsfiddle.net/heruan/0zpqt5kw/

**Comment by zacechola** [comment]
This is not limited to v4, which appears to be an exact port from v3.

Here it is in v3: http://jsbin.com/tazevo/edit?html,output

[This CSS Tricks page is relevant](https://css-tricks.com/fighting-the-space-between-inline-block-elements/).

**Comment by mdo** [comment]
Prolly going to end up floating them everywhere.

**Comment by mdo** [comment]
Fixed in b8c77aaf3b29b1b3d09b3d7bd6ad153d9c315365.

**Comment by francescomazzurco** [comment]
Hi, I am still experiencing the spacing issue in v4.3.1. 
The following breadcrumbs produce different spacings:

```
<ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="#">Home</a></li>
    <li class="breadcrumb-item active">Page</li>
</ol>
<ol class="breadcrumb">
    <li class="breadcrumb-item">
      <a href="#">
        Home
      </a>  
    </li>
    <li class="breadcrumb-item active">
      Page
    </li>
</ol>
```

Codepen: https://codepen.io/francescomazzurco/pen/BaazRLY

Thanks
