### ISSUE TITLE
docs/components/utilities.md rendering issue

### ISSUE THREAD

**Issue by bardiharborow** [twbs/bootstrap#20362]
The lists in [docs/components/utilities.md](https://github.com/twbs/bootstrap/blob/v4-dev/docs/components/utilities.md) are not [rendering correctly](http://v4-alpha.getbootstrap.com/components/utilities/).

**Comment by cvrebert** [comment]
Already fixed in v4-dev branch. Thanks.

**Comment by bardiharborow** [comment]
Is `v4-alpha.getbootstrap.com` not updated instantly? It's quite clearly not fixed there.

**Comment by cvrebert** [comment]
Correct.
v4-alpha.getbootstrap.com corresponds to the latest release version of v4, which is currently v4.0.0-alpha.2, hence why the page footers and the homepage say "Currently v4.0.0-alpha.2".
The fix happened subsequent to that release.
