### ISSUE TITLE
4.0.0-alpha.3 not published to Meteor Atmosphere

### ISSUE THREAD

**Issue by dylannirvana** [twbs/bootstrap#20389]
When trying to add Bootstrap 4 alpha to a Meteor project via the add command, 
meteor add twbs:bootstrap@=4.0.0-alpha.3 
I get the following error:

=> Errors prevented startup:                  
   
   While selecting package versions:
   error: No version of twbs:bootstrap satisfies all constraints:
   @=4.0.0-alpha.3
   Constraints on package "twbs:bootstrap":
   * twbs:bootstrap@=4.0.0-alpha.3 <- top level
   
=> Your application has errors. Waiting for file change.

Thanks in advance for any help.

**Comment by cvrebert** [comment]
@dandv @splendido Looks like autopublish.meteor.com has gone offline?

**Comment by malmosands** [comment]
Still doesn't work for me. I get the following error:

```
=> Errors while parsing arguments:           
                                              
While adding package twbs:bootstrap@=4.0.0-alpha.3:
error: no such version twbs:bootstrap@4.0.0-alpha.3
```

Looks like the package hasn't been updated yet?

**Comment by dylannirvana** [comment]
twbs:bootstrap@=4.0.0-alpha.2 this works. I guess alpha 3 is not yet updated.

**Comment by cvrebert** [comment]
The Meteor package is managed using Atmosphere/Meteor's autopublish service, which appears to be offline for some reason.
In the meantime, you can use Meteor's npm support to install the npm package instead.

**Comment by splendido** [comment]
@cvrebert I'm sorry I've been 'distracted' by other things during the last months and I had no time to follow the evolution of Meteor...
Anyway, autopublish.meteor.com has gone offline when the free deployment of meteor demo as *.meteor.com was discontinued in favour of Galaxy. For some popular packages a free hosting was offered under meteorapp.com, but I got no offer for autopublish.meteor.com

Also, the new support for npm packages is probably enough to replace autopublish.meteor.com?

I'm sorry I had no chances to point this out earlier.
What's your feeling about this?

**Comment by cvrebert** [comment]
Just using npm sounds great to me.

**Comment by splendido** [comment]
Ok, fine!
Feel free to remove the webhook to autopublish.meteor.com

It's been an honour to help you publishing package updates for Meteor :-)

**Comment by dylannirvana** [comment]
I strongly prefer to use Meteor.

**Comment by mdo** [comment]
Was this resolved with subsequent releases?

**Comment by mdo** [comment]
Closing out due to lack of response. Happy to revisit if needed though!

**Comment by lmaddio** [comment]
This wasn't fixed, I also tried `meteor add twbs:bootstrap@=4.0.0-alpha.5`
and its get error saying that version was not found.

**Comment by cvrebert** [comment]
This was resolved as CantFix/WontFix.
Use the npm package instead, now that Meteor supports npm.

Not sure whether the docs were updated accordingly though.

**Comment by bardiharborow** [comment]
@mdo, the meteor install command is still in the docs. Did you want it removed?

**Comment by mdo** [comment]
Sure!
