### ISSUE TITLE
Integrity attribute is incorrect in the documentation

### ISSUE THREAD

**Issue by lilHermit** [twbs/bootstrap#20692]
The integrity attribute is missing the hash algorithm in the docs at http://v4-alpha.getbootstrap.com/getting-started/introduction/.

Reads
`<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.4/js/bootstrap.min.js" integrity="VjEeINv9OSwtWFLAtmc4JCtEJXXBub00gtSnszmspDLCtC0I4z4nqz7rEFbIZLLU" crossorigin="anonymous"></script>`

should be
`<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.4/js/bootstrap.min.js" integrity="sha384-VjEeINv9OSwtWFLAtmc4JCtEJXXBub00gtSnszmspDLCtC0I4z4nqz7rEFbIZLLU" crossorigin="anonymous"></script>`

**Comment by TheBuzzer67** [comment]
Is it the same for the css??
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.4/css/bootstrap.min.css" integrity="sha384-2hfp1SzUoho7/TsGGGDaFdsuuDL0LX2hnUp6VkX3CUQ2K4K+xjboZdsXyp4oUHZj" crossorigin="anonymous">

**Comment by lilHermit** [comment]
I'm not using the css link, I'm building via scss

**Comment by TheBuzzer67** [comment]
Someone will have to explain me how scss works, I tried something and it doesn't work for me, do you have something to read to help me work with SASS files?

**Comment by mdo** [comment]
Fixed by #20694.

**Comment by mdo** [comment]
I pushed a manual fix to our docs, too.

**Comment by KerryRuddock** [comment]
New to bootstrap.  Just wanted to say that this issue still exists under the starter template. 
I used the fixes from the Quick Start section to resolve issue#20692

**Comment by ericrayanderson** [comment]
Second the comment above, issue still exists with start template here:

https://v4-alpha.getbootstrap.com/getting-started/introduction/
