### ISSUE TITLE
data-toggle collapse with data-target selector not using an #id does not update the control's  aria-expanded attribute

### ISSUE THREAD

**Issue by jcwchriswalker** [twbs/bootstrap#21845]
When using a data-toggle='collapse' and data-target selector is not an element id selector, the **aria-expanded** attribute in the control is not updated. However the collapse toggle function works.

Testcase: 
https://jsfiddle.net/jcwchriswalker/c07nv4hs/

1. Both <buttons> control a separate div container. The only difference in the buttons is how the data-target is defined. The 'By ID' button uses a '#collpsediv1' reference and the 'by ClassName' button uses a class selector .collapse.div2 to reference the target
2. Both buttons successfully collapse/uncollapse the target.
3. The <button> **By ID** will correctly set the aria-expanded attribute based on the state of the data-target
4. The <button> **By classname**, does not update its aria-expanded attribute based on the state of the data-target.
5. In both cases, the data-target <div> correctly sets it aria-expanded attribute

**Comment by vanduynslagerp** [comment]
I think it should be fixed by this PR #21654

**Comment by vanduynslagerp** [comment]
I think it's solved by #21692. The main purpose of the PR is to support multi-targets, but it fix this issue because it rely on a different method to determine the trigger of a given `collapse` area.
Currently the methods rely on id only.

**Comment by jcwchriswalker** [comment]
Thanks Pierre- I will be able to try this next week…

**Comment by alecpl** [comment]
This is not fixed. Updated fiddle with 4.3.1 https://jsfiddle.net/3xburgo9/1/

Clicking "By classname" sets `aria-axpanded=true`, but clicking it again will not set it to `aria-expanded=false`. Works with the "By ID" button.

**Comment by kaptajnen** [comment]
I'm seeing a similar issue but instead it seems ALL controls are updated when pressing one of them. Adding an id attribute to the rows fixes the issue: https://jsfiddle.net/auro02ph/

**Comment by mdo** [comment]
https://jsfiddle.net/jcwchriswalker/c07nv4hs/ works as expected for me, `aria-expanded` is toggled in both situations.

@kaptajnen Can you open a new issue for that example? It seems that sharing the classes might be causing that problem... https://jsfiddle.net/9oubjkg1/ has the latest v4.x version in it.

Know I'm a year late here, sorry 😬

**Comment by XhmikosR** [comment]
I'm not sure about this one, but I can confirm @kaptajnen observation.

The original issue does seem to work here too, though.

**Comment by mdo** [comment]
Closing out as stale.
