### ISSUE TITLE
.nav-fill and .nav-justified don't work on the div-based navs

### ISSUE THREAD

**Issue by Studio384** [twbs/bootstrap#21927]
The ```.nav```-documentation seems to suggest that you can switch between ```ul```-based navigation and ```div```-based navigation and continue to use all additional classes, however. On ```div```-based classes, neither ```.nav-fill``` nor ```.nav-justified``` work.

**Comment by mdo** [comment]
Bug reports must include a live demo of the problem. Per our contributing guidelines, please create a reduced test case via [JS Bin](https://jsbinc.om) and report back with your link, Bootstrap version, and specific browser and OS details.

---

_This is a saved reply._

**Comment by mdo** [comment]
Oh snap, nevermind, I see the problem—`.nav-fill` and `.nav-justified` only target the inner `.nav-item`s and not `.nav-link`s. Updating the docs to address this.

**Comment by mdo** [comment]
Fixed by caebfcd.

**Comment by jdahdah** [comment]
This is still broken in your 4.0 docs (3rd example in that section), which appear to be using the beta:
https://getbootstrap.com/docs/4.0/components/navs/#fill-and-justify
