### ISSUE TITLE
Spotted an error on Bootstrap v4 Doc (Modal)

### ISSUE THREAD

**Issue by Prid13** [twbs/bootstrap#22497]
Didn't know where to report the small mistake as I didn't find any contact info, I decided to let you guys know here.

[https://v4-alpha.getbootstrap.com/components/modal/](url)

![image](https://cloud.githubusercontent.com/assets/27897747/25306684/900f3646-2792-11e7-9af9-44e280725f1a.png)

As you can see, the data-target for the button (exampleModal) doesn't match the ID for the modal (myModal). This left me kinda confused as I copy-pasted the code directly while learning how to use modals. If this isn't an error, I apologize beforehand, but at least I tried :)

**Comment by Johann-S** [comment]
Fixed here : https://github.com/twbs/bootstrap/pull/21671

**Comment by Prid13** [comment]
Thanks, didn't know there were so many other who had commented on this as well. However, I still don't SEE the changes effective on the online docs? Am I missing something?

**Comment by rafalp** [comment]
@Prid13 docs are in sync with latest release, and fix is for beta 1 that wasn't released yet.

**Comment by Charlieindex** [comment]
This id is still causing issues for new users.
Any chance of a hotfix in the interim?
