### ISSUE TITLE
[QUESTION] navbar open|close icon throw error "collapse is transitioning"

### ISSUE THREAD

**Issue by subversivo58** [twbs/bootstrap#22527]
I have this error in double tap (mobile) or double click on resized window desktop on close icon

    bootstrap.min.js:6 Uncaught Error: Collapse is transitioning
    at l.show (bootstrap.min.js:6)
    at l.toggle (bootstrap.min.js:6)
    at HTMLDivElement.<anonymous> (bootstrap.min.js:6)
    at Function.each (jquery-3.2.1.min.js:2)
    at r.fn.init.each (jquery-3.2.1.min.js:2)
    at r.fn.init.l._jQueryInterface [as collapse] (bootstrap.min.js:6)
    at HTMLButtonElement.<anonymous> (bootstrap.min.js:6)
    at HTMLDocument.dispatch (jquery-3.2.1.min.js:3)
    at HTMLDocument.q.handle (jquery-3.2.1.min.js:3)

Is there any special reason to throw this error? In **bootstrap.js**

      1102   if (this._isTransitioning) {
      1103       throw new Error('Collapse is transitioning');
      1104   }

      ...

      1179   if (this._isTransitioning) {
      1180       throw new Error('Collapse is transitioning');
      1181   }

Since just after (in both cases) a check whether or not the element has the class "show" and depending on it does a "return".

**Comment by Johann-S** [comment]
Fixed by : https://github.com/twbs/bootstrap/pull/21743

**Comment by subversivo58** [comment]
Sorry for the insistence, I did not understand the "fixed by [#21743](https://github.com/twbs/bootstrap/pull/21743)"

I'm using v4.0.0-alpha.6 and I did not understand the need to throw an error

**Comment by patrickhlauke** [comment]
v4.0.0-alpha.6 is older than the current state of this repository. once the next version (v4 first beta) of bootstrap is released on v4-alpha.getbootstrap.com, the fix https://github.com/twbs/bootstrap/pull/21743 which is already in the current repo will be part of it.

**Comment by xinthose** [comment]
Hello.  I am still getting this error while using the latest CDN:
```
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
```
When will the CDN be updated with this fix?  Or has it been already?

**Comment by wolfy1339** [comment]
@xinthose You're using an outdated version of Bootstrap v4. It is now at version `4.0.0-beta`

**Comment by xinthose** [comment]
@wolfy1339 Thank you.  It works now after using the correct beta CDN, including popper.js, and making the necessary changes from alpha to beta.

**Comment by itd95** [comment]
It's still an issue for those of us who cannot just shift to a new version. I'm doing an enterprise site. I cannot find a reason why this happens, even after checking the commits and implementing an older version of Alpha and reverting back to whatever I did in the past.
