### ISSUE TITLE
Navbar fixed top and modal popup bug

### ISSUE THREAD

**Issue by Softmaker-Ltd** [twbs/bootstrap#22792]
When opening a modal popup on a page with navbar fixed top, the page below the navbar get wrong horizontal adjustment (padding) compared to the navbar above. This only occors if the page has a vertical scrollbar.

Enviroment:
Bootstrap v4.0.0-alpha.6.
IE11 and Google Chrome Versjon 58.0.3029.110 (64-bit).

Please see attached screenshot.
![scrennshot](https://user-images.githubusercontent.com/8394621/27004846-682e16f6-4e11-11e7-828e-e25fea161330.jpg)

**Comment by wolfy1339** [comment]
What version of Windows?

**Comment by Johann-S** [comment]
Fixed here : #18441 and will be available in our next release

**Comment by Softmaker-Ltd** [comment]
Thank you so much Johann-S!

**Comment by Softmaker-Ltd** [comment]
I have just installed Bootstrap v4.0.0-beta, but this bug still occurs. Is this still a known issue?

**Comment by Johann-S** [comment]
yep we fixed a couple of issues about that see : https://github.com/twbs/bootstrap/issues/23278

**Comment by Johann-S** [comment]
I encourage you to try our last dist files :+1:

**Comment by Softmaker-Ltd** [comment]
I use the css files and js files from bootstrap-4.0.0-beta\dist, but still the same problem. When opening a modal popup on a page with navbar fixed top, the page below the navbar get wrong horizontal adjustment (padding) compared to the navbar above. This only occurs if the page has a vertical scrollbar.

**Comment by Johann-S** [comment]
Is it exactly this file ? Downloaded from this URL ? https://raw.githubusercontent.com/twbs/bootstrap/v4-dev/dist/js/bootstrap.min.js

**Comment by Softmaker-Ltd** [comment]
Yes, it is exactly that file. Downloaded bootstrap.min.js from the url you provided again now to be 100% sure, but still the same problem. When the modal is displayed the navbar get wrong horizontal adjustment (padding) compared to the page below. This only occurs when the page has a scrollbar.

**Comment by Johann-S** [comment]
Please provide a reduce test case with a CodePen and I'll reopen this issue

**Comment by Softmaker-Ltd** [comment]
Here is a CodePen test case that shows the bug:
https://codepen.io/softmaker/pen/aLQKve

**Comment by Johann-S** [comment]
Ok I forked your Codepen with our latest change and this bug is still present : https://codepen.io/Johann-S/pen/BwGVvP

**Comment by waclaw66** [comment]
Same in 3.3.7

**Comment by maxoo7** [comment]
> When opening a modal popup on a page with navbar fixed top, the page below the navbar get wrong horizontal adjustment (padding) compared to the navbar above. This only occors if the page has a vertical scrollbar.
> 
> Enviroment:
> Bootstrap v4.0.0-alpha.6.
> IE11 and Google Chrome Versjon 58.0.3029.110 (64-bit).
> 
> Please see attached screenshot.
> ![scrennshot](https://user-images.githubusercontent.com/8394621/27004846-682e16f6-4e11-11e7-828e-e25fea161330.jpg)

This worked for me: https://stackoverflow.com/a/26883617/6063523

Regards!

**Comment by iamandrewluca** [comment]
@waclaw66 see https://github.com/twbs/bootstrap/pull/27331#issuecomment-425366402

**Comment by mattressauthority** [comment]
When opening a modal popup on a page with navbar fixed top, the page below the navbar get wrong horizontal adjustment (padding) compared to the navbar above. This only occors if the [page ](https://gist.github.com/mattressauthority/13b8d120fd4c26844cbf8fc8d5a59812)has a vertical scrollbar.

Enviroment:
Bootstrap v4.0.0-alpha.6.
IE11 and Google Chrome Versjon 58.0.3029.110 (64-bit).

**Comment by mdo** [comment]
This is pretty old, so sorry for digging up a 1.5 year old issue, but I don't see this problem changing in v4 or v5. We're anticipating a specific layout with fixed/sticky top navbars (where they are edge to edge). If you're customizing the layout to not do that with the auto margins, drop the `.fixed-top`/`.sticky-top` and there's no more shifting.

https://codepen.io/emdeoh/pen/jOMpogJ
