### ISSUE TITLE
v4 form input issues

### ISSUE THREAD

**Issue by josephzidell** [twbs/bootstrap#23347]
Two separate issues noticed on Windows 10, in Chrome 60, Firefox 54.0.1, Edge 38. I noticed these in the docs

1. A `<select class="form-control form-control-lg">` needs more height
![screenshot 2017-08-11 09 58 12](https://user-images.githubusercontent.com/1812443/29237470-c275819c-7eec-11e7-9ce2-cb85992f215b.png)

2. Text color is inconsistent between a disabled input vs. select
![screenshot 2017-08-11 10 01 06](https://user-images.githubusercontent.com/1812443/29237475-d9f16fe8-7eec-11e7-8fd6-5e84f16039ea.png)

**Comment by Yeswanth-JG** [comment]
I came to report this. For `select element` below styles might update as below...

### Base Style for `form-control-lg`
```css
.form-control-lg, .input-group-lg>.form-control,
.input-group-lg>.input-group-addon,
.input-group-lg>.input-group-btn>.btn {
    padding: 0.6rem 1rem; /* updated */
    font-size: 1.15rem; /* updated */
    line-height: 1.4; /* updated */
    border-radius: .3rem;
}
```
### height update for `form-control`
```css
select.form-control:not([size]):not([multiple]) {
    height: calc(2.45rem + 2px);
}
```
### height update for `form-control-lg`
```css
.input-group-lg>.input-group-btn>select.btn:not([size]):not([multiple]),
.input-group-lg>select.form-control:not([size]):not([multiple]),
.input-group-lg>select.input-group-addon:not([size]):not([multiple]), select.form-control-lg:not([size]):not([multiple]) {
    height: calc(3.1rem + 2px);
}
```

#### System Details --
Win 7
Chrome - 59.0.3071.115

Above changes update the controls as below.
![image](https://user-images.githubusercontent.com/5590842/29238011-5b47546c-7f48-11e7-98bd-ab656d87f856.png)

**Comment by rorc** [comment]
Yea, text is cutting http://joxi.ru/eAO4PzGt4GpPbr

**Comment by jonnysp** [comment]
Not only the select, also the input, under line glyphs does not display correctly
![g](https://user-images.githubusercontent.com/1651241/29242100-c8c16454-7f86-11e7-8d4b-20a973b185f4.jpg)

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [JS Bin](https://jsbin.com/) or [CodePen](http://codepen.io/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by jonnysp** [comment]
@Johann-S 
https://output.jsbin.com/moyujufara
on latest firefox win 10

**Comment by josephzidell** [comment]
Regular `<select>`s are also cutoff https://jsbin.com/sixiqaruxe/edit?html,output

**Comment by TravellerSam** [comment]
Firefox 55/Linux cuts the input with the standard 1.25 `line-height`. Here an example of a number field:

![bootstrap_4b_input_lineheight125](https://user-images.githubusercontent.com/872730/29674683-2cc96260-88f3-11e7-8cfe-8fe397886b22.png)

Setting the `line-height` slightly higher to 1.35 fixes the issue:

![bootstrap_4b_input_lineheight135](https://user-images.githubusercontent.com/872730/29674828-99877d92-88f3-11e7-8ead-e92360cfc5fd.png)

**Comment by kjdion84** [comment]
Stop closing issues that haven't been addressed or even mentioned in regards to fixing.

**Comment by patrickhlauke** [comment]
@kjdion84 please look at what is being closed, what is being kept open, and what's being cross-referenced and consolidated as a single issue (in this case, THIS one). all you're doing now is generating more noise for people to wade through.

**Comment by kjdion84** [comment]
Having fundamental issues such as text being cutoff in every single `<select>` is worth generating more noise about because its ridiculous that this hasn't been fixed yet.

**Comment by patrickhlauke** [comment]
you seem to misunderstand the idea of how open source run by volunteers works. feel free to send a pull request with fixes.

**Comment by kjdion84** [comment]
Will do thanks for your time.

**Comment by kjdion84** [comment]
Solution:

```
/* fix form control text cutoff */
.form-control {
    line-height: 1.5;
    height: auto !important;
}
```

**Comment by jrysig** [comment]
Note that this problem can be reproduced with free Windows virtual machines from Microsoft, see https://github.com/twbs/bootstrap/issues/23769#issuecomment-331377830

**Comment by dracos** [comment]
Note I believe the issue of height cut off was fixed by https://github.com/twbs/bootstrap/pull/23150 as there is a bug with the `form-control-lg` height in the current beta (which the above examples are using). I'm afraid it's quite hard to work this out from the git history though.

The padding issue of #24043 (marked as duplicate of this) is still present in current v4-dev. This has a couple of parts:
* Options have a little bit of unremovable magic left padding in Chrome, Firefox, (maybe Safari?);
* Padding on select is e.g. ignored on desktop Chrome and Safari (but is followed in Firefox), and (sort of) honoured on Android Chrome.
So the left padding needs to be 3px(?) less for selects than inputs in order to align with text inputs, except it still won't in desktop Chrome/Safari as they ignore it whatever it is. The only way everything could always line up would be if the left-padding was fixed, at whatever size, at whatever desktop Chrome/Safari are using as their unchangeable value.

**Comment by Johann-S** [comment]
already fixed with our last dist files see : https://codepen.io/Johann-S/pen/MEpBdR

**Comment by kjdion84** [comment]
It isn't fixed properly. The issue still exists for even normal selects in Chrome on Windows.

Characters are still being cut off as the text is still not centered vertically properly.

Proof fiddle: https://codepen.io/anon/pen/WZpPPp
Proof image: [Imgur](https://i.imgur.com/JLH8mad.jpg)

**Comment by mdo** [comment]
Can y'all test out the changes in #24199?

**Comment by jrysig** [comment]
#24199 looks good! Tested with latest DEV Bootstrap version.

W7 and IE11:
![w7_ie11](https://user-images.githubusercontent.com/7038517/31064654-dfa370d8-a73e-11e7-9012-b349a9161a31.png)

W7 and Chrome:
![w7_chrome](https://user-images.githubusercontent.com/7038517/31064676-02ea8586-a73f-11e7-8bcc-902a8dd97ceb.png)

**Comment by jrysig** [comment]
There is one problem in DEV Bootstrap version:

Windows 7, Internet Explorer 11, see different input and input-group-addon height
![w7_ie11](https://user-images.githubusercontent.com/7038517/31065377-ff64d0be-a744-11e7-9693-3914628b795e.png)

It works fine in latest Chrome and Firefox. Should I report it as a separate issue?

**Comment by dracos** [comment]
* #24199 does fix the default form-control being cut off at the bottom, yes :-)
* The disabled text colour being different for inputs/selects (original issue part 2) is still present
* The left-padding being different for different controls (#24043, closed as a dupe of this) is still present, but as I commented at https://github.com/twbs/bootstrap/issues/23347#issuecomment-332493174 it doesn't really sound easily fixable.

Thanks!

(@jrysig, my personal suggestion would be yes to a separate issue, makes it easier to track.)

**Comment by kjdion84** [comment]
@mdo it looks much better and also scales well with `-lg`.

**Comment by mdo** [comment]
@jrysig That should be fixed as of #23810.

**Comment by mdo** [comment]
@josephzidell @dracos The different text color is because the `<input>` is using a `placeholder` vs the select menu showing an `<option>`. Selects don't support `placeholder` attributes.

**Comment by dracos** [comment]
@mdo Makes sense! The original text of this issue is fixed, therefore, yes, the only issue is the left padding.
