### ISSUE TITLE
Web page has wrong installation instructions for ruby

### ISSUE THREAD

**Issue by jcoyne** [twbs/bootstrap#23465]
<img width="409" alt="screen shot 2017-08-15 at 9 56 05 am" src="https://user-images.githubusercontent.com/92044/29321434-07da5d42-81a0-11e7-8e59-d1aaa8ef4be3.png">

it should say `gem install bootstrap -v 4.0.0.beta`

**Comment by XhmikosR** [comment]
It's already fixed in v4-dev.

/CC @mdo

**Comment by jcoyne** [comment]
@XhmikosR that's great, but it's not fixed on the live site yet, so shouldn't this stay open until then?

**Comment by XhmikosR** [comment]
It's the same thing, really. @mdo will update it when he will update it. The issue is already fixed in the repo and that's what we track.
