### ISSUE TITLE
Broken Documentation Links

### ISSUE THREAD

**Issue by santiph** [twbs/bootstrap#24016]
Link sin the new documentation are broken.
Current version of [Webpack documentation file](https://github.com/twbs/bootstrap/blob/v4-dev/docs/4.0/getting-started/webpack.md) (as for 716e124) contains
```
[Install bootstrap]({{ site.baseurl }}/docs/{{ site.docs_version }}/getting-started/download/#npm)
```
which is producing (and leading to a 404 page)
```
<a href="/getting-started/download/#npm">Install bootstrap</a>
```
instead of
```
<a href="/docs/4.0/getting-started/download/#npm">Install bootstrap</a>
```

**Comment by andresgalante** [comment]
Thanks for reporting it 😄  It was fixed here:
https://github.com/twbs/bootstrap/commit/537b5f012771069b182aabab651eff9723d785b0

**Comment by santiph** [comment]
Cool! How long would it take to impact on https://getbootstrap.com/docs/4.0/getting-started/webpack/ ? It has been more than a month since that has been merged, but links are still broken

**Comment by andresgalante** [comment]
@santiph when beta-2 gets release it'll impact the website

**Comment by santiph** [comment]
oh, nice...
Is there any release schedule published?

**Comment by andresgalante** [comment]
I don't know. This might help https://github.com/twbs/bootstrap/projects/4
