### ISSUE TITLE
Some characters cannot show well in select list when it is placed under card-body

### ISSUE THREAD

**Issue by applelok** [twbs/bootstrap#24392]
**Environment:**
OS: Windows
Browser: Found the problem in both Chrome Version 61.0.3163.100  and Firefox 52.3.0

**Problem description:**
Found that when I add the "drop down select list" (Select option) inside the card-body,
some of the characters cannot be displayed well, like g, p... etc (Referring to the screen capture below, I tried to test in bootstrap 4 beta documentation page but still cannot display those characters)

![image](https://user-images.githubusercontent.com/11794100/31604751-d6b520a8-b296-11e7-9d17-84132d32359a.png)

It should be the problem of padding inside form-control class, when it is placed under card-body.

**Reproduce:**
Created a pen and tried to update the padding from .5rem .75rem, to .4em .75em
Those characters (g/j/l/p/q/y) can be displayed well.
https://codepen.io/anon/pen/QqZYbV

**Comment by Johann-S** [comment]
Seems already fixed with our current dist files : https://codepen.io/Johann-S/pen/QqZYOY

**Comment by applelok** [comment]
Hi @Johann-S ,

May I ask when will this fix (included in the current dist file) be deployed to public?
Since the problem is still here when I am using the latest bootstrap version "4.0.0-beta" in my project.

Thank you.

**Comment by Johann-S** [comment]
Sorry but we don't know when we will ship our next release, but the only thing I can say it's, it will be soon

**Comment by applelok** [comment]
Got it, thank you for your quick response! ;) @Johann-S
