### ISSUE TITLE
Blank space between slides - Carousel

### ISSUE THREAD

**Issue by leskam** [twbs/bootstrap#24657]
In browser Firefox Beta (58.0) I found a bug in Bootstrap Carousel. Between slides there are a blank space like on photo. Probably new Firefox CSS engine cant render fine bootstrap CSS.

![carousel-bug](https://user-images.githubusercontent.com/33346738/32370128-3ac02b44-c08c-11e7-8b3b-71ebab526d7d.png)

[CodePen](https://codepen.io/Uzumymw95/pen/xPZMXJ) live test.

Details:
Bootstrap 4 beta.2
Firefox 58.0a1 (build 2017-11-02) x64
Windows 10 ver. 1703 x64

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by Uzumymw95** [comment]
Sorry, updated first post.

**Comment by Grukdon** [comment]
I'm experiencing the same thing, running on FF58.0b1 (developer edition). I'm thinking it's a browser bug because I swear it was working on FF57...
 
Curious though, if you scroll through the carousel backwards (with left arrow), does it work normally/smoothly for you?

**Comment by Uzumymw95** [comment]
Yes, it works fine on FF57, and when I use carousel control arrows.

**Comment by NTpspE** [comment]
I'm having the same issue, works fine in every other browser and version - but when I use firefox developer edition I get white space between slides. 

Oddly, if I show the developer tools it generally fixes itself.

**Comment by uclnj** [comment]
Confirmed with Firefox 58.0b10 (64-bit).  The blank space only appears when sliding from right to left (forward motion.)  When sliding left to right, the slides transition properly.  The transition in Chrome/Edge/IE works as expected with the occasional white line between slides in Edge.

**Comment by fabriziobertoglio1987** [comment]
I am experiencing this when testing the carousel on my Chrome Android 5.1 Device. I am hosting the app on https://surfcheck.herokuapp.com/ and this is the [github of the project](https://github.com/fabriziobertoglio1987/surfcheck), while here is the [code from the carousel](https://github.com/fabriziobertoglio1987/surfcheck/blob/master/app/views/posts/_carousel.html.haml)

I installed the latest bootstrap 4 with yarn. You can test this issue by going to my page https://surfcheck.herokuapp.com/ with a mobile device using `chrome 62.0.3202.84`

**Comment by iangregory** [comment]
Mozilla have a bug open for this: [#1425213](https://bugzilla.mozilla.org/show_bug.cgi?id=1425213)

**Comment by anantajitjg** [comment]
Same issue for me with Bootstrap 4 in FF 58.0

**Comment by neralex** [comment]
Firefox updated to 59.0 - the animation is a bit fast than before but the issue still exists.

**Comment by Mibeon** [comment]
Yes, the issue is stil there. Also just updated firefox to latest (59) version.
Please fix it fast. We want to use this el in production.

**Comment by XhmikosR** [comment]
This should be fixed in v4-dev. It'd be nice if someone could confirm.

**Comment by XhmikosR** [comment]
Closing for now, since it should be fixed in v4-dev. If not leave a comment.

**Comment by mdo** [comment]
I still managed to see issues with these half pixels in Firefox with the above patch.

**Comment by mdo** [comment]
Unclear what the scope of this issue remains. I put together https://codepen.io/emdeoh/pen/dypqxZQ with v4.5.3, which if you click quickly between the indicators, you'll see a brief flash of blue _sometimes_ in the latest Firefox for macOS (as well as Safari fwiw). Making the change from above would undo #27594 effectively, so I'm unsure how best to proceed, if at all.

if folks are still seeing this issue, let's get a new, fresh issue opened with a solid demo that can demonstrate the issue. Thanks!
