### ISSUE TITLE
Padding/alignment issue when using a .container within .navbar-expand-* responsive navbar

### ISSUE THREAD

**Issue by davidtmiller** [twbs/bootstrap#24726]
When using a container within a responsive navbar, it seems that the padding is being removed - which is necessary under the xs breakpoint, <576px. Between the xs breakpoint and wherever the navbar is collapsing however, the padding seems a bit off.

I located the portion of the SCSS that is responsible for this. In the `_navbar.scss` file, I found:

```
      @include media-breakpoint-down($breakpoint) {
        > .container,
        > .container-fluid {
          padding-right: 0;
          padding-left: 0;
        }
      }
```

Which, when using `navbar-expand-lg` for example, sets the left and right margins to 0 at 991px and below.

Now I am not super familiar with the Bootstrap SASS setup, so I was unable to produce a fix in the Bootstrap SASS, but I created a messy override that was a working solution to this alignment problem.

**Default View**
![1](https://user-images.githubusercontent.com/8400627/32570316-c8804b68-c491-11e7-93f0-6bec625dde54.png)

Live Demo on CodePen:
https://codepen.io/davidtmiller/pen/wPoNBm

The fix is just some SASS I added after loading Bootstrap:
```
.navbar-expand-lg,
.navbar-expand-md,
.navbar-expand-sm,
.navbar-expand-xl {
  > .container,
  > .container-fluid {
    padding-left: 15px;
    padding-right: 15px;
    @media (max-width: 575px) {
      padding-left: 0;
      padding-right: 0;
    }
  }
}
```

With this fix, the collapsed navbar aligns with the rest of the page content, and continues to align correctly after the xs breakpoint is reached.

**After Fix**
![2](https://user-images.githubusercontent.com/8400627/32570433-19227e10-c492-11e7-86d4-4462af8c2178.png)

Live Demo on CodePen:
https://codepen.io/davidtmiller/pen/MObLwR

Again I'm not quite sure how to approach this in the SASS files, I know the answer will be shifting some things around with the `_navbar.scss` file, like adding a `media-breakpoint-min` mixin or something like that.

System Info:
- Mac OS X Sierra
- Most Recent Chrome/Firefox/Safari

**Comment by Johann-S** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by davidtmiller** [comment]
Here is the default behavior:

Size the preview to <992px to see the navbar collapse.
https://codepen.io/davidtmiller/pen/wPoNBm

Here is the behavior with the fix proposed above (again make sure to size the preview to <992px):
https://codepen.io/davidtmiller/pen/MObLwR

**Comment by istratos** [comment]
Same issue as reported here but it just got ignored: https://github.com/twbs/bootstrap/issues/22471
Can confirm it still exists, any os any browser.

**Comment by davidtmiller** [comment]
@istratos Thanks for finding this, I missed it in my search!

**Comment by agriffis** [comment]
As a longer-term fix, since it's impossible to affect navbar styling by matching on a nested container, you could add a .navbar-container class to zero the navbar padding. Then kill the code that manipulates the container padding. Like this:

```diff
diff --git a/scss/_navbar.scss b/scss/_navbar.scss
index 05025273f..57ccc5801 100644
--- a/scss/_navbar.scss
+++ b/scss/_navbar.scss
@@ -23,6 +23,11 @@
   justify-content: space-between; // space out brand from logo
   padding: $navbar-padding-y $navbar-padding-x;

+  &.navbar-container {
+    padding-left: 0;
+    padding-right: 0;
+  }
+
   // Because flex properties aren't inherited, we need to redeclare these first
   // few properities so that content nested within behave properly.
   > .container,
@@ -142,15 +147,11 @@
     $next: breakpoint-next($breakpoint, $grid-breakpoints);
     $infix: breakpoint-infix($next, $grid-breakpoints);

+    // On the final pass through the loop,
+    // $breakpoint = xl, $next = null, $infix = "",
+    // effectively wrapping around from xl to xs,
+    // therefore generating rules for bare .navbar-expand.
     &#{$infix} {
-      @include media-breakpoint-down($breakpoint) {
-        > .container,
-        > .container-fluid {
-          padding-right: 0;
-          padding-left: 0;
-        }
-      }
-
       @include media-breakpoint-up($next) {
         flex-flow: row nowrap;
         justify-content: flex-start;
```

and then use it like this:

```html
    <nav class="navbar navbar-container navbar-expand navbar-light bg-light">
        <div class="container">
            ...
        </div>
    </nav>
```

**Comment by johnunclesam** [comment]
@agriffis the code posted here (https://github.com/twbs/bootstrap/issues/22471#issuecomment-338770768) doesn't work for you? If it does, can you make a PR with that code?

**Comment by XhmikosR** [comment]
@MartijnCuppens can you confirm this is still an issue?

**Comment by istratos** [comment]
The issue still exists, it never got fixed.

**Comment by pedzed** [comment]
I can confirm this. @davidtmiller Thank you for your bug report, the image precisely describes the problem.

Changing `navbar-expand-md` to `navbar-expand-sm` seems to work in my use case.

**Comment by iamandrewluca** [comment]
Sooo.. :) Using `.container .navbar` and `.navbar .container` should behave the same?  
Content should be aligned on every screen size?  Can someone confirm this? Thanks.
![image](https://user-images.githubusercontent.com/1881266/48337118-bd33a380-e66a-11e8-97ad-cebadb31953c.png)

**Comment by SueIte** [comment]
We do have this issue as well, I would love it if this issue would be fixed without me using a workaround.

**Comment by hracik** [comment]
Still issue in version 4.4.1

**Comment by MartijnCuppens** [comment]
This is fixed in v5 by requiring containers in the navbar. For v4, you can use utilities to fix this.

**Comment by kdion4891** [comment]
Still happening.

Only reasonable fix is to add `px-md-3` to the container inside the navbar e.g.:

    <nav class="navbar navbar-expand navbar-light">
        <div class="container px-md-3">
