### ISSUE TITLE
IE11 + 4.1: JavaScript runtime error: Object.keys: argument is not an Object

### ISSUE THREAD

**Issue by Alessandro3325** [twbs/bootstrap#26320]
After upgrading my project to bootstrap 4.1 I get a JavaScript runtime error: Object.keys: argument is not an Object in Internet Explorer 11.

This can be simply reproduced by opening http://getbootstrap.com/ in IE 11!

![bootstrap4 1](https://user-images.githubusercontent.com/32120724/38857018-6da038b0-4228-11e8-8bbe-b2c98858fa4d.png)

**Comment by Johann-S** [comment]
Already fixed by: https://github.com/twbs/bootstrap/pull/26291 and will be available in our next release 👍

**Comment by AmbiTews** [comment]
Hi All,
I am still getting error Object.keys: argument is not an Object , I have IE version 11.1805.15063.0

**Comment by Johann-S** [comment]
Hi @AmbiTews you have to update your Bootstrap version the latest is v4.3.1
