### ISSUE TITLE
Caching problems still exist on v4.1.1 docs

### ISSUE THREAD

**Issue by sts-ryan-holton** [twbs/bootstrap#26441]
@mdo I'm still experiencing this problem, cleared browser cache multiple times, have been checking throughout the day, in particular on this page is a good test -> https://getbootstrap.com/docs/4.1/components/carousel/

the indicators for the carousel. Try clearing your browser cache, it'll then work, but refresh normally after that and cursor: pointer is missing which I assume is related to some additional cache problems?

**Comment by sts-ryan-holton** [comment]
@mdo any update on this?

**Comment by mdo** [comment]
Every page I've tested, now across two countries and multiple devices (sorry, I've been traveling!), hasn't had an issue with redirects, stale components, or the search form. Very few people seem to be having this issue, too, as evidenced by the referenced issues here and in your original one. I'm not sure what else I can do as I already purged CloudFlare's cache on our end last week.

**Comment by sts-ryan-holton** [comment]
@mdo  I've just done some experimenting, clearing the browser cache and then normally reloading the browser (what most devs are likely to do) doesn't actually clear the cache on the Bootstrap docs for some reason.

I found, that if I clear my browser cache and then completely close the browser and reopen the browser it then manages to show the correct version of Bootstrap 4.1.1

Tested on Google Chrome on Mac

```
Right click + inspect element, right click the refresh button and choose to clear the cache, then restart the browser.
```

I've never had to do this before, and based on the issues referenced above I'm sure others are finding this difficult too, maybe we could consider letting people know?

**Comment by sts-ryan-holton** [comment]
@mdo 

Weirdly, I just noticed....

Try this...

Go to `http://getbootstrap.com/` and it will load the new version.

But head to `https://getbootstrap.com/` (secure) and it loads the older version.

Also, the search still points to 4.1.0

**Comment by rafalp** [comment]
I can confirm that `https` points to Bootstrap 4.1.0 whereas `http` points to 4.1.1

**Comment by sts-ryan-holton** [comment]
Weird behaviour, most new people to bootstrap are likely to google for Bootstrap and click the link pointing to https whereas us developers and the Bootstrap dev team are likely to type `getbootstrap.com` into the URL and thus not likely experience the issue.

**Comment by wolfy1339** [comment]
There is an `http` to `https` redirect, so I'm not sure how you got that.
I don't experience any issue at all with the docs. It displays the right version

**Comment by sts-ryan-holton** [comment]
@wolfy1339 simply typed in the URL `getbootstrap.com` - didn't get redirected at all, this issue is still present

**Comment by rafalp** [comment]
> There is an http to https redirect, so I'm not sure how you got that.

This is false. I'm not being redirected at all.

**Comment by wolfy1339** [comment]
I still can't reproduce at all even on plain HTTP

**Comment by rafalp** [comment]
What kind of caching is employed? Perhaps european ussers are experiencing the issue because we hit different spot in CDN?

**Comment by mdo** [comment]
Is this service worker related or something @XhmikosR?

**Comment by XhmikosR** [comment]
@mdo: I have no idea since I was never able to reproduce...

/CC @gauntface @addyosmani @Lyricalz : do you happen to have any ideas if it's indeed service worker related?

**Comment by coliff** [comment]
for what its worth- I'm in Japan and can report the following is true for me;

- http://getbootstrap.com is not redirecting to https://getbootstrap.com
- https://getbootstrap.com/ is showing 4.1.0
- http://getbootstrap.com/ is showing 4.1.1
- Docs search results always shows 4.0 (even from a 4.1 docs page)

Tested on Windows 10 Chrome 66 and macOS Chrome 66

**Comment by XhmikosR** [comment]
The https redirect does not happen because @mdo never enabled this.

**Comment by XhmikosR** [comment]
@mdo: somewhere you broke the docs when you changed the assets.

1. the 4.1 docs (at least) are missing the brand images
2. You are missing the vendor JS files thus leading to an error which might explain this
    `NetworkError: Failed to load worker script at "/assets/js/vendor/workbox-sw.js"`

**Comment by Lyricalz** [comment]
If it's only happening on https, then it's definitely the service worker is still caching the original redirect response from `/`.

This file gives me a 404 on incognito: https://getbootstrap.com/assets/js/vendor/workbox-sw.js probably why the service worker won't update

**Comment by coliff** [comment]
@XhmikosR - oh yep, I see: https://github.com/twbs/bootstrap/issues/23262
It'd be good to have always on HTTPS with HSTS.

**Comment by XhmikosR** [comment]
I've bugged Mark countless times and I plan to do so until everything is
https only  :). But please don't mix different issues

**Comment by sts-ryan-holton** [comment]
Still experiencing Cache problems, any idea when this will be fixed?

**Comment by coliff** [comment]
hey @sts-ryan-holton - open Chrome Devtools, open Application tab and then Application > Clear Storage. Then tap the 'Clear site data' button to wipe service worker storage etc. That'll fix it for you.

**Comment by sts-ryan-holton** [comment]
@coliff  Awesome, that seemed to work. How are we going to do this for other users though? Most users aren't going to do it that way? Is there a way to automate this on new releases?

**Comment by Lyricalz** [comment]
@XhmikosR I can revisit the service worker PR and implement a proper "update" feature for new releases?

**Comment by XhmikosR** [comment]
Please do so and ping me!

**Comment by XhmikosR** [comment]
@Lyricalz: while at it, how about we cache bust the workbox-sw.js? Not sure what workbox does out of the box, but it makes sense. Maybe they have an API for this?

**Comment by XhmikosR** [comment]
@mdo needs to update the docs to fix the current issue.

**Comment by mdo** [comment]
Hoping with the close of #23262 this should be resolved. Can folks verify?

**Comment by XhmikosR** [comment]
Mark, please check my comments above. You missed copying all the JS assets
with the docs refactoring.

**Comment by XhmikosR** [comment]
@Lyricalz: any updates?

BTW, I was thinking, can't we switch to local hosting the workbox files like in older versions but still use `injectManifest()`?

**Comment by mdo** [comment]
I enabled the redirection, but had to disable it as the https enforcement affects our Themes and Jobs sites, breaking our iframes and more. Still have to dig into that more.

**Comment by mark-zacharias** [comment]
what in the actual fuck. remove your service worker until this is fixed.  It causes much pain!
I can see in the dev tools that the service worker claims to have last received data on 11/24/2017, 3:34:14 PM.

**Comment by Lyricalz** [comment]
@mark-zacharias Why don't you contribute then?
