### ISSUE TITLE
.nav .flex-column and collapse - problem with display block

### ISSUE THREAD

**Issue by SkuterPL** [twbs/bootstrap#26567]
Hi,
I want to create Vertical navbar with collapse on mobile phone, so I wrote this code:

`				<div class="col-md-3">
					<h2 data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo" role="button">Mapa strony</h2>
						<ul class="nav .flex-column collapse" id="collapseTwo" aria-labelledby="headingTwo" data-parent="#accordion">
							<?php
							foreach ($menu as $index => $menu_one) {
								echo '<li class="nav-item"><a href="/' .$menu_one['alias']. '.html" class="nav-link">' . $menu_one['name_' . lang('nazwa') . ''] . '</a></li>';
							}
							?>
						</ul>
				</div>`

But when I click my h2 button I am getting problem with class .show because it is `display: block` and in `.flex-column' class has `!important`. 

I tried to delete `.flex-column' class from `ul` element and add this code directly to the nav element to delete `!important`, but still problem exsists, because of `display: block`.

I read this issue: https://github.com/twbs/bootstrap/pull/22758 but this new class `.flexshow` is only added when detect `.row`.

Maybe you should add some fix for `.flex-column` or maybe anyone know the best way to fix that?

Regards,
Tomek

**Comment by mdo** [comment]
Issues are for bug reports and feature requests, not general how-to questions. For that, we suggest the official Slack channel or Stack Overflow. Both are linked from our readme.

Thanks!

**Comment by SkuterPL** [comment]
But this is issue, this code should work.

**Comment by mdo** [comment]
Then please follow the issue template and provide a live demo of the issue, as well as additional browser, OS, and Bootstrap version details.

**Comment by ysds** [comment]
Fixed in v4.1 #25806

**Comment by SkuterPL** [comment]
No, there is no fix for that. I updated my jsfiddle and you can see that bug still exist. This fix which you sent was when parent is `.row`, but in my code there is no `.row`, just `.flex-column`.

**Comment by ysds** [comment]
Your demo still using v4.0.0. And then, You must add `.flex-nowrap`.

**Comment by SkuterPL** [comment]
You have right, I clicked update, but I don't know why code wasn't updated.

https://jsfiddle.net/a9qfd06x/ Now it works okey, but why I had to add `.flex-nowrap`?

PS 
Do you know how to disable collapse on defined resolution (because I want to use collapse only on mobile version)?
