### ISSUE TITLE
Floating label placeholder not hiding when focus on input

### ISSUE THREAD

**Issue by man88100ni** [twbs/bootstrap#34671]
1. Windows 10, chrome, firefox etc
2. When click on input the placeholder don't hide label overlaps the placeholder. It's not the same as shown on bootstrap official site. Please have a look on the screenshot attached. [ http://prntscr.com/1ixzzbl ]

Thanks,
Manish Soni

**Comment by nathan-appere** [comment]
Same issue in Chrome 92.0.4515.131 (Big Sur)

**Comment by solida333** [comment]
Hi, when I click on somewhere near the Floating label input (on the left or right side) it's always get focus.
Chrome: Version 92.0.4515.131
this issued not see it in Firefox: 91.0

**Comment by man88100ni** [comment]
I saw that the issue was fixed automatically I did nothing and the issue gone. Now its working fine at my end but how its possible don't know?

**Comment by solida333** [comment]
Oh! still happen to me and also in Bootstrap website doc - https://getbootstrap.com/docs/5.1/forms/floating-labels/
I think this issues because of Browser.

**Comment by man88100ni** [comment]
but I was using the same browser before the issue and after that also

**Comment by man88100ni** [comment]
> Hi, when I click on somewhere near the Floating label input (on the left or right side) it's always get focus.
> Chrome: Version 92.0.4515.131
> this issued not see it in Firefox: 91.0

Its working fine at my end the link you provided of bootstrap website doc. on both Chrome Version (92.0.4515.131) and Firefox (Version 90.0.2)

**Comment by nathan-appere** [comment]
I tried without Chrome extensions, and on my end I think ProWritingAid was the culprit. I only experience the issue when re-installing it.

**Comment by solida333** [comment]
This is the video that i click somewhere. near the Floating Label and it also get focus.
https://youtu.be/Ef7xHpMEYAY

**Comment by mdo** [comment]
Closing as no longer an issue.
