### ISSUE TITLE
Scrolling not working when offcanvas is removed (even if disposed is called)

### ISSUE THREAD

**Issue by Harvey1214** [twbs/bootstrap#36397]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

If an offcanvas has been opened and we'd like to remove the element by first disposing the offcanvas instance and then removing the element from the DOM, the scrollbar disappears and scrolling is disabled (overflow: hidden stays on the body). We believe that when dispose is called and then the element is deleted, this shouldn't happen.

This issue occurred in all browsers it was tested in.

### Reduced test cases

Please take a look at this codepen where the issue has been reproduced: https://codepen.io/harvey1214/pen/dydWgOB

1. Click "Open offcanvas"
2. Offcanvas gets opened
3. Click "Remove offcanvas"
4. Element is removed and scrolling is frozen, scrollbars disappear

You can see this issue in a real-world scenario in our Blazor Bootstrap component library: https://localhost:44376/components/HxOffcanvas#Backdrop Open the offcanvas and then click the "Source" tab, scrolling will be frozen.

This is also an issue for the developers using this library: https://github.com/havit/Havit.Blazor/issues/110

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Microsoft Edge

### What version of Bootstrap are you using?

v5.1.3

**Comment by mdo** [comment]
This should be addressed in v5.2.0-beta1. Stable release is coming soon.

**Comment by hakenr** [comment]
The issue is not fixed, please reopen the ticket.

The `dispose()` method fails to reset scrollbars, leaving `overflow: hidden` on the `body` element intact. Neither `Offcanvas.js:dispose()` nor `Modal.js:dispose()` invoke `ScrollBarHelper().reset()`.

Currently, this reset is only triggered in the `hide()` logic of Bootstrap's Offcanvas/Modal. However, this approach is ineffective for us because Blazor (SPA) removes elements from the DOM, causing the `hide()` call to fail before `scrollbar.reset()` can be executed.

**Comment by hakenr** [comment]
Steps to Reproduce:
1. Open (show) an Offcanvas/Modal within the SPA.
2. Navigate to a different screen within the SPA, which results in the removal of the Offcanvas/Modal elements from the DOM (for example, by clicking the BACK button in the browser).
3. During navigation, execute `dispose()` for cleanup. Since the elements are already being removed from the DOM, it's not possible to call `hide()` in this context.
4. Observe that `overflow:hidden` remains applied to the `body` element because `ScrollBarHelper.reset()` is not included in the disposal logic.

...the `dispose()` should do the cleanup even if the offcanvas/modal was shown.
