### ISSUE TITLE
React Build Fails with 5.2

### ISSUE THREAD

**Issue by pipe2k27** [twbs/bootstrap#36851]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

React Build Fails when using bootstrap 5.2 and trying to parse SCSS files. Rolled back to 5.1.3 version and build runs fine. 
Console shows parserError: Syntax error but nothing is wrong with the file. When running the project locally it is fine too! Just trying to build breaks the code. 

Any help or insight will be appreciated

Thank you very much!!

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.2.0

**Comment by tetuaoro** [comment]
Same problems like @pipe2k27 when I cloned my repo from another computer. I modified the `package.json` to use v5.1.3.
Here the build output : 

```bash
Import trace for requested module:
./styles/globals.scss
./pages/_app.tsx

./styles/globals.scss
SassError: Undefined variable.
    ╷
142 │       values: $utilities-border-colors
    │               ^^^^^^^^^^^^^^^^^^^^^^^^
```

The variable `$utilities-border-colors` is `undefined`.

**Comment by mdo** [comment]
You have to include the new maps.scss file. See the blog post for details: https://blog.getbootstrap.com/2022/07/19/bootstrap-5-2-0/.

**Comment by ahmadasjad** [comment]
Even after adding maps.scss, I'm getting `ParserError: Syntax Error at line: 1, column 38`
Working fine when commented/removed some of the components.

These are the culprits

- `@import "../node_modules/bootstrap/scss/list-group";`
- `@import "../node_modules/bootstrap/scss/toasts";`
- `@import "../node_modules/bootstrap/scss/modal";`
- `@import "../node_modules/bootstrap/scss/popover";`

Below is custom.scss

```
// 1. Include functions first (so you can manipulate colors, SVGs, calc, etc)
@import "../node_modules/bootstrap/scss/functions";

// 3. Include remainder of required Bootstrap stylesheets
@import "../node_modules/bootstrap/scss/variables";

// 4. Include any default map overrides here

// 5. Include remainder of required parts
@import "../node_modules/bootstrap/scss/maps";

@import "../node_modules/bootstrap/scss/mixins";
@import "../node_modules/bootstrap/scss/utilities";
@import "../node_modules/bootstrap/scss/root";

// 6. Optionally include any other parts as needed
@import "../node_modules/bootstrap/scss/reboot";
@import "../node_modules/bootstrap/scss/type";
@import "../node_modules/bootstrap/scss/images";
@import "../node_modules/bootstrap/scss/containers";
@import "../node_modules/bootstrap/scss/grid";
@import "../node_modules/bootstrap/scss/tables";
@import "../node_modules/bootstrap/scss/forms";
@import "../node_modules/bootstrap/scss/buttons";
@import "../node_modules/bootstrap/scss/transitions";
@import "../node_modules/bootstrap/scss/dropdown";
@import "../node_modules/bootstrap/scss/button-group";
@import "../node_modules/bootstrap/scss/nav";
@import "../node_modules/bootstrap/scss/navbar";
@import "../node_modules/bootstrap/scss/card";
@import "../node_modules/bootstrap/scss/breadcrumb";
@import "../node_modules/bootstrap/scss/pagination";
@import "../node_modules/bootstrap/scss/badge";
@import "../node_modules/bootstrap/scss/alert";
@import "../node_modules/bootstrap/scss/progress";
// @import "../node_modules/bootstrap/scss/list-group";
@import "../node_modules/bootstrap/scss/close";
// @import "../node_modules/bootstrap/scss/toasts";
// @import "../node_modules/bootstrap/scss/modal";
@import "../node_modules/bootstrap/scss/tooltip";
// @import "../node_modules/bootstrap/scss/popover";
@import "../node_modules/bootstrap/scss/carousel";
@import "../node_modules/bootstrap/scss/spinners";
@import "../node_modules/bootstrap/scss/helpers";

// 7. Optionally include utilities API last to generate classes based on the Sass map in `_utilities.scss`
@import "../node_modules/bootstrap/scss/utilities/api";

// 8. Add additional custom code here
```

**Comment by mcmillion** [comment]
I'm seeing the same thing as @ahmadasjad so I'm not sure why this is closed.

I'm not doing any custom imports, just `@import "~bootstrap/scss/bootstrap";` like the docs say and I get the same error: `ParserError: Syntax Error at line: 1, column 38`

**Comment by mdo** [comment]
Any chance someone can create a live example in Stackblitz that we could test with? I'm on vacation and don't have time to do this myself.

**Comment by tungphan995** [comment]
Thank you for believing in me.

**Comment by afrz** [comment]
My 2 cents. I have the same problem using CRA 4.0.3 + Dart-SASS 1.54.4 for Bootstrap 5.2.

Seems that is related to following issue [bootstrap 1496](https://github.com/sass/dart-sass/issues/1496).
Somehow [postcss-values-parser](https://github.com/shellscape/postcss-values-parser/issues/138) in the toolchain can not figure out some SASS syntax correctly.

Bootstrap 5.1.2 has introduce workounds [here](https://github.com/twbs/bootstrap/blob/v5.1.3/scss/mixins/_grid.scss#L11) but Bootstrap 5.2 has not ([like here](https://github.com/twbs/bootstrap/blob/v5.2.0/scss/_nav.scss#L65)).

When I remove such SASS lines, I have no more parser errors.

**Comment by tagliala** [comment]
@afrz is this problem only related to `margin` rules?

In other word, does it compile if the multiplication is left as-is in rules like `box-shadow`?

https://github.com/twbs/bootstrap/blob/337068f8b1044004f4b9abfffbb433694ae87993/scss/_accordion.scss#L50

**Comment by pipe2k27** [comment]
Still having the issue. Maps import did not solve. only downgrading to 5.1.3 will make build pass.

**Comment by pipe2k27** [comment]
We do have a custonBootstrap file where we override default bootstrap and that seems to be the issue. whenever you try to import  @import '../../../node_modules/bootstrap/scss/bootstrap'; build will fail

**Comment by julien-deramond** [comment]
> Any chance someone can create a live example in Stackblitz that we could test with?

**Comment by tagliala** [comment]
Hi,

I have a reproducible (not-so-reduced) test case

```sh
$ rails _6.1.6.1_ new syntax-error-webpacker --skip-active-record --skip-javascript
$ cd syntax-error-webpacker/
$ echo "{ \"private\": true }" > package.json
$ echo "gem 'webpacker', '5.4.3'" >> Gemfile
$ bundle
$ bundle exec rails webpacker:install
$ yarn add bootstrap @popperjs/core
$ echo "@import \"~bootstrap/scss/bootstrap\";" > app/javascript/packs/application.scss
$ NODE_ENV=production bin/webpack # does not happen in development
```

Output:
```
ERROR in ./app/javascript/packs/application.scss (./node_modules/css-loader/dist/cjs.js??ref--6-1!./node_modules/postcss-loader/src??ref--6-2!./node_modules/sass-loader/dist/cjs.js??ref--6-3!./app/javascript/packs/application.scss)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
ParserError: Syntax Error at line: 1, column 38
    at ~/dev/tests/syntax-error-webpacker/app/javascript/packs/application.scss:6:65128
    at Parser.error (~/dev/tests/syntax-error-webpacker/node_modules/postcss-values-parser/lib/parser.js:127:11)
    at Parser.operator (~/dev/tests/syntax-error-webpacker/node_modules/postcss-values-parser/lib/parser.js:162:20)
    at Parser.parseTokens (~/dev/tests/syntax-error-webpacker/node_modules/postcss-values-parser/lib/parser.js:245:14)
    at Parser.loop (~/dev/tests/syntax-error-webpacker/node_modules/postcss-values-parser/lib/parser.js:132:12)
    at Parser.parse (~/dev/tests/syntax-error-webpacker/node_modules/postcss-values-parser/lib/parser.js:51:17)
    at parse (~/dev/tests/syntax-error-webpacker/node_modules/postcss-custom-properties/index.cjs.js:47:30)
    at ~/dev/tests/syntax-error-webpacker/node_modules/postcss-custom-properties/index.cjs.js:333:24
    at ~/dev/tests/syntax-error-webpacker/node_modules/postcss/lib/container.js:194:18
    at ~/dev/tests/syntax-error-webpacker/node_modules/postcss/lib/container.js:139:18
    at Rule.each (~/dev/tests/syntax-error-webpacker/node_modules/postcss/lib/container.js:105:16)
    at Rule.walk (~/dev/tests/syntax-error-webpacker/node_modules/postcss/lib/container.js:135:17)
    at ~/dev/tests/syntax-error-webpacker/node_modules/postcss/lib/container.js:152:24
    at Root.each (~/dev/tests/syntax-error-webpacker/node_modules/postcss/lib/container.js:105:16)
    at Root.walk (~/dev/tests/syntax-error-webpacker/node_modules/postcss/lib/container.js:135:17)
    at Root.walkDecls (~/dev/tests/syntax-error-webpacker/node_modules/postcss/lib/container.js:192:19)
    at transformProperties (~/dev/tests/syntax-error-webpacker/node_modules/postcss-custom-properties/index.cjs.js:330:8)
    at Object.syncTransform [as plugin] (~/dev/tests/syntax-error-webpacker/node_modules/postcss-custom-properties/index.cjs.js:522:5)
    at ~/dev/tests/syntax-error-webpacker/node_modules/postcss-preset-env/index.js:459:97
 @ ./app/javascript/packs/application.scss 2:26-228
 @ multi ./app/javascript/packs/application.js ./app/javascript/packs/application.scss
```

A draft PR to workaround this issue is available at #37079, but this probably needs a sort of check to prevent addition of new calculations that break postcss-values-parser

**Comment by julien-deramond** [comment]
_For future self, need to `sudo gem install rails -v 6.1.6.1` as first step._

I confirm that the issue shown in the reproductible steps and that the draft PR fix the compilation (thanks a lot @tagliala for that) so @mdo I'm reopening the issue for further investigations; I need to check why we rollbacked the inversion of negative value multipicators in `calc()`.

**Comment by tagliala** [comment]
Welcome!

> _For future self, need to `sudo gem install rails -v 6.1.6.1` as first step._

Will fix instructions

> I need to check why we rollbacked the inversion of negative value multipicators in `calc()`.

Don't know if it is a rollback. Some values are still inverted in v5.2.0 as pointed out in https://github.com/twbs/bootstrap/issues/36851#issuecomment-1219468651

https://github.com/twbs/bootstrap/blob/edf9c40956d19e6ab3f9151bfe0dfac6be06fa21/scss/mixins/_grid.scss#L11-L13

I wonder why if a custom linter can be implemented to check this problem in advance

**Comment by julien-deramond** [comment]
Some modifications linked to the errors in the history:
- [accordions](https://github.com/twbs/bootstrap/commit/efc59146671bb671993353cc1f0a0daff1bfe554#diff-5d9695a786bb36821feb277b5ae21bff4b34d1232058fd7f6dec684250e71928)
- [list groups](https://github.com/twbs/bootstrap/commit/63145c8bc6bb26f7651fbd6cfe626068704cdf76)

As you said @tagliala it doesn't seem to be a rollback but rather something we have forgotten along the way or we weren't aware of (authors/reviewers of PRs).
I'll double-check the PR but it seems to fix the issue already.

> I wonder why if a custom linter can be implemented to check this problem in advance

Would be great indeed to avoid reintroducing issues that we can't be aware of with our current CI. I don't have any ideas atm on how to do that. Feel free to propose something if you have any idea :)

**Comment by tagliala** [comment]
As far as I can tell, `calc($sass-variable * -1)` works fine and the problem is only with css variables and negative values.

I think this has been involuntarily introduced in 5.2.0 because of the migration to CSS variables. Example from #34622

https://github.com/twbs/bootstrap/pull/34622/files#diff-784199f5a3b8476a11197627a5c80662fb117f6039b7feac1c472f2ed3d04d26R63

> Feel free to propose something if you have any idea :)

I only have in mind a regular expression and that is definitely a bad idea prone to false positives :(

**Comment by afrz** [comment]
> @afrz is this problem only related to `margin` rules?

No as you figure it out already I guess :) 

> As far as I can tell, `calc($sass-variable * -1)` works fine and the problem is only with CSS variables and negative values.

Yes, it seems the problem is combining `calc()` with a CSS variable multiplied by negative values.
Reversing the order of the multiplication arguments should do the trick !

**Comment by pipe2k27** [comment]
This issue has been solved with 5.2.1 Thanks everyone for support and help! much appreciated!

**Comment by kevinhq** [comment]
@pipe2k27 

> This issue has been solved with 5.2.1 Thanks everyone for support and help! much appreciated!

This is still happening on `5.2.3`. Exactly same error when running `rake assets:precompile`

**Comment by tagliala** [comment]
Hi @kevinhq, I can't confirm

```
$ gem install rails -v 7.0.4.3 # If Rails 7.x is not installed. sudo may be needed
$ rails _7.0.4.3_ new syntax-error-webpacker --skip-active-record --skip-javascript
$ cd syntax-error-webpacker/
$ echo "{ \"private\": true }" > package.json
$ echo "gem 'webpacker', '5.4.4'" >> Gemfile
$ bundle
$ bundle exec rails webpacker:install
$ yarn add bootstrap @popperjs/core
$ echo "@import \"~bootstrap/scss/bootstrap\";" > app/javascript/packs/application.scss
$ NODE_ENV=production RAILS_ENV=production rails assets:precompile
```

Output:
```
Compiling...
Compiled all packs in /Users/geremia/dev/tests/syntax-error-webpacker/public/packs
Hash: 6c9bb683e16bb72f8e62
Version: webpack 4.46.0
Time: 2545ms
Built at: 03/25/2023 12:27:09 PM
                                        Asset       Size  Chunks                                Chunk Names
       js/application-f94efae3d24600285e6e.js    728 KiB       0  [emitted] [immutable]  [big]  application
    js/application-f94efae3d24600285e6e.js.br   73.6 KiB          [emitted]                     
    js/application-f94efae3d24600285e6e.js.gz    120 KiB          [emitted]                     
   js/application-f94efae3d24600285e6e.js.map    757 KiB       0  [emitted] [dev]               application
js/application-f94efae3d24600285e6e.js.map.br   79.2 KiB          [emitted]                     
js/application-f94efae3d24600285e6e.js.map.gz    127 KiB          [emitted]                     
                                manifest.json  364 bytes          [emitted]                     
                             manifest.json.br  129 bytes          [emitted]                     
                             manifest.json.gz  142 bytes          [emitted]                     
Entrypoint application [big] = js/application-f94efae3d24600285e6e.js js/application-f94efae3d24600285e6e.js.map
[0] multi ./app/javascript/packs/application.js ./app/javascript/packs/application.scss 40 bytes {0} [built]
[1] ./app/javascript/packs/application.js 845 bytes {0} [built]
[2] ./app/javascript/packs/application.scss 664 bytes {0} [built]
[4] ./node_modules/css-loader/dist/cjs.js??ref--6-1!./node_modules/postcss-loader/src??ref--6-2!./node_modules/sass-loader/dist/cjs.js??ref--6-3!./app/javascript/packs/application.scss 724 KiB {0} [built]
    + 2 hidden modules

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  js/application-f94efae3d24600285e6e.js (728 KiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  application (728 KiB)
      js/application-f94efae3d24600285e6e.js
```

I've also a repository that works (but I cannot test on heroku at the moment) https://github.com/diowa/ruby3-rails7-bootstrap-heroku

**Comment by kevinhq** [comment]
> You have to include the new maps.scss file. See the blog post for details: https://blog.getbootstrap.com/2022/07/19/bootstrap-5-2-0/.

@tagliala no worry. I just tried this one, and it works. Thanks.
