### ISSUE TITLE
Tooltips with native HTML title attribute not working on dynamically created elements

### ISSUE THREAD

**Issue by Nudasoft** [twbs/bootstrap#36895]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Tooltips with data-bs-title attribute works fine. but with native title attribute not working on dynamically added elements.

### Reduced test cases

with native html title attribute
https://jsfiddle.net/h4w3018g/

with data-bs-title attribute
https://jsfiddle.net/q1n7Levo/

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.2.0

**Comment by GeoSot** [comment]
Hello @Nudasoft 


I suppose is fixed on #36751

Try this script on your code and please feedback me 
`https://deploy-preview-36751--twbs-bootstrap.netlify.app/docs/5.2/dist/js/bootstrap.bundle.min.js`

**Comment by Nudasoft** [comment]
Hi @GeoSot 

Unfortunately the problem is still exists.

https://jsfiddle.net/Lhy57xeg/

**Comment by Jayteezany** [comment]
Hi, i want to help fix the problem

**Comment by tungphan995** [comment]
Thank you for believing in me.
