### ISSUE TITLE
"Color mode" docs refer to non-existent "Sass usage" section

### ISSUE THREAD

**Issue by EccentricVamp** [twbs/bootstrap#38067]
### Prerequisites

- [x] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [x] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

The Bootstrap 5.3 documentation for "color modes" has a couple broken links.

### Expected behavior

* If the section doesn't exist yet then the links should be removed.
* If the section does exist then the links should work.

### Steps to reproduce
1. Go to https://getbootstrap.com/docs/5.3/customize/color-modes/
2. Scroll to the [CSS variables](https://getbootstrap.com/docs/5.3/customize/color-modes/#variables) or [Sass mixin](https://getbootstrap.com/docs/5.3/customize/color-modes/#sass-mixin) sections
3. Try to click on "[can be configured](https://getbootstrap.com/docs/5.3/customize/color-modes/#sass-usage)" or "[Sass usage section](https://getbootstrap.com/docs/5.3/customize/color-modes/#sass-usage)" links

### P.S.
The existing bug report template requires a "live demo" which doesn't really apply to bugs in the Bootstrap site itself. Consider adding another issue template or provide instructions in the contributing guidelines for opening issues that don't fit the mold.

**Comment by julien-deramond** [comment]
Thanks for opening this issue @EccentricVamp. Those links are already fixed in our _main_ branch as you can see in https://twbs-bootstrap.netlify.app/docs/5.3/customize/color-modes/#variables and https://twbs-bootstrap.netlify.app/docs/5.3/customize/color-modes/#sass-mixin.

So I'm closing it.

We can continue the discussion regarding the bug report template. Thanks for the feedback btw.
We could maybe change the description of the "Reduced test cases" section.

Now it is:

> Include links [reduced test case](https://css-tricks.com/reduced-test-cases/) links or suggested fixes using CodePen ([v4 template](https://codepen.io/team/bootstrap/pen/yLabNQL) or [v5 template](https://codepen.io/team/bootstrap/pen/qBamdLj)).

Could be something like that:

> Include links [reduced test case](https://css-tricks.com/reduced-test-cases/) links or suggested fixes using CodePen ([v4 template](https://codepen.io/team/bootstrap/pen/yLabNQL) or [v5 template](https://codepen.io/team/bootstrap/pen/qBamdLj)). If the issue is linked to Bootstrap documentation itself, include these links here.

What do you think?
Adding another issue template would add too much complexity IMO.

**Comment by EccentricVamp** [comment]
I'd like to refer some of my co-workers to the documentation, but the link is still broken at https://getbootstrap.com/docs/5.3/customize/color-modes/. Should I start using the Netlify app as the official documentation?

I think the changes to the bug report template make sense. I agree that a new issue template would add complexity and possibly confusion for users.

**Comment by EccentricVamp** [comment]
The checkbox for "I have [validated](https://html5.validator.nu/) any HTML to avoid common problems" is also irrelevant for bugs in the Bootstrap site

**Comment by julien-deramond** [comment]
> Should I start using the Netlify app as the official documentation?

The official documentation remains https://getbootstrap.com. The Netlify link is only the deployment of our current _main_ branch. The links will be fixed when we will release the new alpha version for the v5.3.0.

Thanks for the feedback regarding the issues. I'll see what I can do.
