### ISSUE TITLE
SASS deprecation warnings with version 1.77.7 - Mixed declarations

### ISSUE THREAD

**Issue by apepper** [twbs/bootstrap#40621]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Using the latest version of the `sass` package (`1.77.7`) there are deprecation warnings by `sass`. The previous `sass` version `1.77.6` worked fine.

### Reduced test cases

* Upgrade sass (`npm i sass@latest`)
* Execute `npm run css-compile`

*Expected*:
```
npm run css-compile

> bootstrap@5.3.3 css-compile
> sass --style expanded --source-map --embed-sources --no-error-css scss/:dist/css/
```

*Actual*:
```
npm run css-compile

> bootstrap@5.3.3 css-compile
> sass --style expanded --source-map --embed-sources --no-error-css scss/:dist/css/

Deprecation Warning: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.

More info: https://sass-lang.com/d/mixed-decls

    ┌──> scss/_reboot.scss
503 │     font-weight: $legend-font-weight;
    │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ declaration
    ╵
    ┌──> scss/vendor/_rfs.scss
136 │ ┌     @media (#{$rfs-mq-property-width}: #{$rfs-mq-value}) {
137 │ │       @content;
138 │ │     }
    │ └─── nested rule
    ╵
    scss/_reboot.scss 503:3          @import
    scss/bootstrap-reboot.scss 10:9  root stylesheet

Deprecation Warning: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.

More info: https://sass-lang.com/d/mixed-decls

    ┌──> scss/_reboot.scss
504 │     line-height: inherit;
    │     ^^^^^^^^^^^^^^^^^^^^ declaration
    ╵
    ┌──> scss/vendor/_rfs.scss
136 │ ┌     @media (#{$rfs-mq-property-width}: #{$rfs-mq-value}) {
137 │ │       @content;
138 │ │     }
    │ └─── nested rule
    ╵
    scss/_reboot.scss 504:3          @import
    scss/bootstrap-reboot.scss 10:9  root stylesheet

Deprecation Warning: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.

More info: https://sass-lang.com/d/mixed-decls

    ┌──> scss/_reboot.scss
503 │     font-weight: $legend-font-weight;
    │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ declaration
    ╵
    ┌──> scss/vendor/_rfs.scss
136 │ ┌     @media (#{$rfs-mq-property-width}: #{$rfs-mq-value}) {
137 │ │       @content;
138 │ │     }
    │ └─── nested rule
    ╵
    scss/_reboot.scss 503:3   @import
    scss/bootstrap.scss 16:9  root stylesheet

Deprecation Warning: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.

More info: https://sass-lang.com/d/mixed-decls

    ┌──> scss/_reboot.scss
504 │     line-height: inherit;
    │     ^^^^^^^^^^^^^^^^^^^^ declaration
    ╵
    ┌──> scss/vendor/_rfs.scss
136 │ ┌     @media (#{$rfs-mq-property-width}: #{$rfs-mq-value}) {
137 │ │       @content;
138 │ │     }
    │ └─── nested rule
    ╵
    scss/_reboot.scss 504:3   @import
    scss/bootstrap.scss 16:9  root stylesheet

Deprecation Warning: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.

More info: https://sass-lang.com/d/mixed-decls

    ┌──> scss/_type.scss
38  │       font-family: $display-font-family;
    │       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ declaration
    ╵
    ┌──> scss/vendor/_rfs.scss
136 │ ┌     @media (#{$rfs-mq-property-width}: #{$rfs-mq-value}) {
137 │ │       @content;
138 │ │     }
    │ └─── nested rule
    ╵
    scss/_type.scss 38:5      @import
    scss/bootstrap.scss 17:9  root stylesheet

Deprecation Warning: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.

More info: https://sass-lang.com/d/mixed-decls

    ┌──> scss/_type.scss
39  │       font-style: $display-font-style;
    │       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ declaration
    ╵
    ┌──> scss/vendor/_rfs.scss
136 │ ┌     @media (#{$rfs-mq-property-width}: #{$rfs-mq-value}) {
137 │ │       @content;
138 │ │     }
    │ └─── nested rule
    ╵
    scss/_type.scss 39:5      @import
    scss/bootstrap.scss 17:9  root stylesheet

Deprecation Warning: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.

More info: https://sass-lang.com/d/mixed-decls

    ┌──> scss/_type.scss
40  │       font-weight: $display-font-weight;
    │       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ declaration
    ╵
    ┌──> scss/vendor/_rfs.scss
136 │ ┌     @media (#{$rfs-mq-property-width}: #{$rfs-mq-value}) {
137 │ │       @content;
138 │ │     }
    │ └─── nested rule
    ╵
    scss/_type.scss 40:5      @import
    scss/bootstrap.scss 17:9  root stylesheet

Warning: 22 repetitive deprecation warnings omitted.
Run in verbose mode to see all warnings.
```

### What operating system(s) are you seeing the problem on?

macOS

### What version of Bootstrap are you using?

Latest `main` branch

**Comment by ajiho** [comment]
I have also encountered this issue. My project, or adminlte, also requires some scss files that rely on bootstrap. If you want to eliminate this warning, I asked if you should release bootstrap 5.3.4 so that we can obtain scss files without warnings?

**Comment by martn001** [comment]
I have encountered the same issues with my Vue/Vuetify project. Currently, I am receiving more then 100 deprecation warnings for the latest version of the Vuetify package `^3.6.12`. 😅

```
Deprecation Warning: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.

More info: https://sass-lang.com/d/mixed-decls

  ┌──> node_modules/vuetify/lib/styles/tools/_typography.sass
3 │     font-weight: $font-weight
  │     ^^^^^^^^^^^^^^^^^^^^^^^^^ declaration
  ╵
  ┌──> node_modules/vuetify/lib/styles/tools/_position.sass
3 │ ┌     &--#{$position}
4 │ │       position: #{$position} if($important, !important, null)
  │ └─── nested rule
  ╵
    node_modules/vuetify/lib/styles/tools/_typography.sass 3:3           typography()
    node_modules/vuetify/lib/components/VSystemBar/VSystemBar.sass 23:5  @content
    node_modules/vuetify/lib/styles/tools/_layer.scss 9:5                layer()
    node_modules/vuetify/lib/components/VSystemBar/VSystemBar.sass 4:1   @use
    plugin-vuetify:components/VSystemBar/VSystemBar.sass 2:1            root stylesheet
```

**Comment by euro** [comment]
FYI 1.77.8 of Dart Sass is out.
https://github.com/sass/dart-sass/releases/tag/1.77.8

**Comment by tang2087** [comment]
Getting same warning for my Nuxt project.

**Comment by Asmmmir** [comment]
I got latest version of bootstrap, but I still got warnings

**Comment by dkrnl** [comment]
`npm i sass@1.77.6 --save-exact`

**Comment by du-disk** [comment]
i found same issue, how to fix please

**Comment by troovi** [comment]
Guaranteed way to solve the problem:

Comment all all function calls that include **Sassx27s** match in `node_modules/sass/saas.dart.js`

<img width="1028" alt="Screenshot 2024-07-14 at 23 37 52" src="https://github.com/user-attachments/assets/e50dca67-ff46-4d3f-a98c-d4b9c741bf0e">


I even used quietDeps:true in the webpack scss setup, but it didn't help. So the only solution was to find and comment out the lines causing the annoying waring

**Comment by bobitza** [comment]
> i found same issue, how to fix please



> `npm i sass@1.77.6 --save-exact`

It's worked

**Comment by cotiga** [comment]
While waiting a fix... Edit the line in "package.json"
`"sass": "^1.74",`
by :
`"sass": "1.77.6",`
and do :
`npm update`

**Comment by kejedi** [comment]
downgrading from `1.77.8` to `1.74` does not resolve the issue

y'all REALLY want me to use tailwind huh

**Comment by jdavidbakr** [comment]
The issue appears to throw warnings but still builds for me ... but warnings are never fun to have.  Hoping this gets an update soon.

**Comment by Krisslk** [comment]
> `npm i sass@1.77.6 --save-exact`

thanks machan

**Comment by frontierFlight** [comment]
https://sass-lang.com/documentation/breaking-changes/mixed-decls/

**Comment by vasiliy-l** [comment]
For now, we can silence the warning until Bootstrap v5.3.4 is released https://github.com/twbs/bootstrap/issues/40651#issuecomment-2242902437

This can be done by using `silenceDeprecations` option. https://sass-lang.com/documentation/js-api/interfaces/options/#silenceDeprecations

Configs changes for webpack:
```js
module.exports = {
  // ...

  module: {
    rules: [
      // ...

      {
        test: /\.s?[ac]ss$/i,
        use: [
          'style-loader',
          'css-loader',
          'postcss-loader',
          {
            loader: 'sass-loader',
            options: {
              sassOptions: {
                silenceDeprecations: ['mixed-decls'],
              },
            },
          },
        ],
      },
    ],
  },
};
```

**Comment by martn001** [comment]
> I have encountered the same issues with my Vue/Vuetify project. Currently, I am receiving more then 60 different deprecation warnings for the latest version of the Vuetify package `^3.6.12`. 😅
> 
> ```
> Deprecation Warning: Sass's behavior for declarations that appear after nested
> rules will be changing to match the behavior specified by CSS in an upcoming
> version. To keep the existing behavior, move the declaration above the nested
> rule. To opt into the new behavior, wrap the declaration in `& {}`.
> 
> More info: https://sass-lang.com/d/mixed-decls
> 
>   ┌──> node_modules/vuetify/lib/styles/tools/_typography.sass
> 3 │     font-weight: $font-weight
>   │     ^^^^^^^^^^^^^^^^^^^^^^^^^ declaration
>   ╵
>   ┌──> node_modules/vuetify/lib/styles/tools/_position.sass
> 3 │ ┌     &--#{$position}
> 4 │ │       position: #{$position} if($important, !important, null)
>   │ └─── nested rule
>   ╵
>     node_modules/vuetify/lib/styles/tools/_typography.sass 3:3           typography()
>     node_modules/vuetify/lib/components/VSystemBar/VSystemBar.sass 23:5  @content
>     node_modules/vuetify/lib/styles/tools/_layer.scss 9:5                layer()
>     node_modules/vuetify/lib/components/VSystemBar/VSystemBar.sass 4:1   @use
>     plugin-vuetify:components/VSystemBar/VSystemBar.sass 2:1            root stylesheet
> ```

The issue I encountered with my Vue/Vuetify project has been resolved by Vuetify. They fixed the problem in a newer version. So, if you run into these issues, the solution for Vue/Vuetify projects is to upgrade the Vuetify package from '^3.6.12' to '^3.6.14'.

![image](https://github.com/user-attachments/assets/eb356074-c27c-4dc2-ab9d-ca31fd18eee9)

**Comment by deepak-gangwar** [comment]
## Found a solution ✅
I fixed all the warnings by shifting my mixins to the end of styles. (There were a lot 🤯)

Earlier, this was giving me deprecation warnings:

```scss
 &__title {
    @include title-font;
    padding: 23px;

    @include bp-desktop {
      padding: 3vw 0 0;
    }
    
    &-inner {
      font-weight: normal';
    }
  }
```

You can see the bp-desktop and nested style is already at end, however the font mixin is before a normal padding style. Doing the following across the whole project fixed all warnings.

```scss
 &__title {
    padding: 23px;
    @include font-headline;

    @include bp-desktop {
      padding: 3vw 0 0;
    }
    
    &-inner {
      font-weight: normal';
    }
  }
  ```
  
I believe if you have any mixins or  nested styles, move them after the regular styles. Put all regular styles at the start of the block. I hope this helps. 😊

**Comment by RinNguyens** [comment]
> `npm i sass@1.77.6 --save-exact`

it worked for meee. Tks bro

**Comment by rajcracker** [comment]
It's working for me  Thanks 
`npm i sass@1.77.6 --save-exact`

**Comment by pratik149** [comment]
> I believe if you have any mixins or nested styles, move them after the regular styles. Put all regular styles at the start of the block.

Thank you @deepak-gangwar. You are right, I didn't need to downgrade or anything. Simply following the instruction provided in the warning helps resolve all the warnings.  ✅

**Comment by hackel** [comment]
FYI, to disable the deprecation warnings with Vite:
```js
export default defineConfig(() => ({
  css: {
    preprocessorOptions: {
      scss: {
        silenceDeprecations: ['mixed-decls'],
      },
    },
  },
}));
```

**Comment by tang2087** [comment]
> FYI, to disable the deprecation warnings with Vite:
> 
> ```js
> export default defineConfig(() => ({
>   css: {
>     preprocessorOptions: {
>       scss: {
>         silenceDeprecations: ['mixed-decls'],
>       },
>     },
>   },
> }));
> ```

This is a good solution. I have updated for my Nuxt app:

```
export default defineNuxtConfig({
   devtools: { enabled: false },
   ssr: false,
   vite: {
      css: {
         preprocessorOptions: {
            scss: {
               silenceDeprecations: ["mixed-decls"]
            }
         }
      }
   },

}

```

**Comment by olivarjoseluis** [comment]
> `npm i sass@1.77.6 --save-exact`

It's work for me, thank you!

**Comment by Mahedi-Hasan10** [comment]
> `npm i sass@1.77.6 --save-exact`

Thank you so much. Its worked.

**Comment by themeix** [comment]
It worked after change sass version `npm i sass@1.77.6 --save-exact `

**Comment by kauemurakami** [comment]
> npm i sass@1.77.6 --save-exact

It worked here, ty !

**Comment by evgeniy-vashchuk** [comment]
For everyone using Gulp who wants to temporarily hide these warnings, there is **silenceDeprecations** option for this:
```
.pipe(sass({
    silenceDeprecations: ['legacy-js-api', 'mixed-decls', 'color-functions', 'global-builtin', 'import'],
    outputStyle: config.isProd ? 'compressed' : 'expanded',
    indentType: 'space',
    indentWidth: 2,
    includePaths: ['./node_modules']
}).on('error', plugins.notify.onError({ title: 'Error compiling SASS' })))
```

**Comment by jules-w2** [comment]
Hey @julien-deramond  

do you have an ETA for a 5.3.4 release of bootstrap?

Bests

**Comment by julien-deramond** [comment]
Hey.
Unfortunately, no.
I'm not the release manager, so I'm waiting for https://github.com/twbs/bootstrap/pull/40656 too

**Comment by kjjd84** [comment]
RELEASE THE KRAKEN

IT FEELS GROSS USING v1.77.6 JUST TO GET RID OF TERMINAL WARNING SPAM

**Comment by M4rckR** [comment]
> Para todos aquellos que usan Gulp y desean ocultar temporalmente estas advertencias, existe la opción **silenceDeprecations** para esto:
> 
> ```
> .pipe(sass({
>     silenceDeprecations: ['legacy-js-api', 'mixed-decls', 'color-functions', 'global-builtin', 'import'],
>     outputStyle: config.isProd ? 'compressed' : 'expanded',
>     indentType: 'space',
>     indentWidth: 2,
>     includePaths: ['./node_modules']
> }).on('error', plugins.notify.onError({ title: 'Error compiling SASS' })))
> ```

Interesting

**Comment by petschki** [comment]
It feels more and more like giving a dead horse the spurse here? Sorry 🤷🏼‍♂️

**Comment by sadnaastasia** [comment]
> `npm i sass@1.77.6 --save-exact`

Thanks a lot!!!!! It really works!!!!!

**Comment by apepper** [comment]
@mdo, @XhmikosR and @patrickhlauke: Is there chance, that we get a `5.3.4` release any time soon? `5.3.3` is now almost a year old and this issue is already fixed since half a year ago. A release would be much appreciated!

**Comment by kai-dorschner-twinsity** [comment]
> The bootstrap team is not active anymore

How did you come to this conclusion? That's polemic.
![image](https://github.com/user-attachments/assets/2a634812-ca94-4b8c-bfed-25586aa727da)

**Comment by danon** [comment]
I don't understand why this issue is closed, since the newest bootstrap 5.3.3 still issues warnings on scss.

**Comment by TheSeg** [comment]
> I don't understand why this issue is closed, since the newest bootstrap 5.3.3 still issues warnings on scss.

My guess is the assumption that warnings can be ignored it means it's "fixed". But ignoring warnings doesn't mean an issue is fixed, just punted to break in an inoperable degree in the near future.

**Comment by apepper** [comment]
> I don't understand why this issue is closed, since the newest bootstrap 5.3.3 still issues warnings on scss.

It is closed, since the issue is already fixed in `master`. But sadly the bootstrap release seems to be stuck (see https://github.com/twbs/bootstrap/pull/40656 and https://github.com/twbs/bootstrap/issues/40621#issuecomment-2577599204).

**Comment by VBproDev** [comment]
It's currently 2025, and the warnings are still appearing. When is this going to be fixed?

**Comment by DYW972** [comment]
> > `npm i sass@1.77.6 --save-exact`
> 
> Thanks a lot!!!!! It really works!!!!!

Thanks ! This will do until the new version out

**Comment by apepper** [comment]
@XhmikosR I just saw, that you updated https://github.com/twbs/bootstrap/pull/40656 recently. Is there any ETA when `v5.3.4` will be released? Is there any blocker? A timely release would be much appreciated.

**Comment by lukasjuhrich** [comment]
To anyone not subscribed to releases, `v5.3.4` has been released four days ago (and `v5.3.5` the next day). To anyone else, sorry for the ping!

**Comment by VBproDev** [comment]
@lukasjuhrich I have upgraded to `5.3.5` yet I'm still facing the issue

**Comment by kjjd84** [comment]
this has been an issue for almost a year, i could have had a pr submitted and merged to fix this in a day

is this ever going to be released, if not you might as well put a 401 redirect of the bootstrap website to tailwindcss.com

**Comment by patrickhlauke** [comment]
> i could have had a pr submitted and merged to fix this in a day

why didn't you then?

**Comment by kjjd84** [comment]
hey yall, looks like this isn't ever going to get fixed

in the meantime you can add this to your vite config to get rid of the terminal spam:

```js
export default defineConfig({
    css: {
        preprocessorOptions: {
            scss: {
                silenceDeprecations: [
                    "mixed-decls",
                    "color-functions",
                    "global-builtin",
                    "import",
                ],
            },
        },
    },
});
```
